
SET DATEFORMAT DMY
CREATE DATABASE ThiThucHanh

-- 1
CREATE TABLE DOCGIA
(
MADG CHAR(6) PRIMARY KEY, 
HOTEN VARCHAR(35), 
NGAYSINH SMALLDATETIME, 
DIACHI VARCHAR(35), 
SODT VARCHAR(15)
)
CREATE TABLE SACH 
(
MASACH CHAR(6) PRIMARY KEY, 
TENSACH VARCHAR(25), 
THELOAI VARCHAR(25), 
NHAXUATBAN VARCHAR(35)
)
CREATE TABLE PHIEUTHUE
(
MAPT CHAR(6) PRIMARY KEY, 
MADG CHAR(6) FOREIGN KEY REFERENCES DOCGIA(MADG), 
NGAYTHUE SMALLDATETIME,
NGAYTRA SMALLDATETIME ,
SOSACHTHUE INT 
)
CREATE TABLE CHITIET_PT 
(
MAPT CHAR(6) FOREIGN KEY REFERENCES PHIEUTHUE(MAPT), 
MASACH CHAR(6) FOREIGN KEY REFERENCES SACH(MASACH),
CONSTRAINT PK_CHITIET_PT PRIMARY KEY (MAPT, MASACH)
)

----2
--2. Hiện thực các ràng buộc toàn vẹn sau:
--2.1. Nhà xuất bản chỉ có thể là 'Văn Lang', 'Hàng Hải', 'Hồng Đức', 'Lao động', 'Nhã Nam'. (1 đ)
ALTER TABLE SACH ADD CONSTRAINT CK_NXB CHECK (NHAXUATBAN IN ( 'Văn Lang', 'Hàng Hải', 'Hồng Đức', 'Lao động', 'Nhã Nam' ))
--2.2. Mỗi lần thuê sách, đọc giả không được thuê quá 10 ngày. (1 đ)
ALTER TABLE PHIEUTHUE ADD CONSTRAINT CK_THOIGIANTHUE CHECK (NGAYTRA - NGAYTHUE <= 10)
--3. Viết các câu lệnh SQL thực hiện các câu truy vấn sau:
--3.1. Tìm các đọc giả (MaDG,HoTen) đã thuê sách thuộc thể loại 'Văn học' trong năm 2020. (1 đ)
SELECT DG.MADG, DG.HOTEN
FROM CHITIET_PT LEFT JOIN PHIEUTHUE PT ON CHITIET_PT.MAPT = PT.MAPT
JOIN SACH ON CHITIET_PT.MASACH = SACH.MASACH
JOIN DOCGIA DG ON PT.MADG = DG.MADG
WHERE SACH.THELOAI = 'Văn học' AND YEAR(PT.NGAYTHUE) = 2020
--3.2. In ra tất cả đọc giả và thông tin sách họ thuê nếu có. (1 đ)
SELECT DISTINCT DG.MADG, DG.HOTEN, 
SACH.MASACH, SACH.TENSACH, SACH.THELOAI, SACH.NHAXUATBAN
FROM DOCGIA DG LEFT JOIN PHIEUTHUE PT ON DG.MADG = PT.MADG
LEFT JOIN CHITIET_PT CTPT ON PT.MAPT= CTPT.MAPT
LEFT JOIN SACH ON SACH.MASACH = CTPT.MASACH
--3.3. Tìm phiếu thuê ít sách nhất năm 2019. (1 đ)
SELECT * 
FROM PHIEUTHUE
WHERE SOSACHTHUE = 
(SELECT MIN(SOSACHTHUE) SLSACHTHUE
 FROM PHIEUTHUE 
 WHERE (YEAR(NGAYTHUE) = 2019 
 OR YEAR(NGAYTRA)=2019))
--3.4. Tìm tên đọc giả thuê các sách thuộc thể loại 'Tin học' và 'Giáo dục'. (1 đ)
SELECT DISTINCT D.MADG, D.HOTEN
FROM DOCGIA D JOIN PHIEUTHUE P ON D.MADG = P.MADG
JOIN CHITIET_PT C ON C.MAPT = P.MAPT
JOIN SACH S ON S.MASACH = C.MASACH
WHERE THELOAI = 'Tin học' OR THELOAI = 'Giáo dục'
--3.5. Tìm số lượng sách được thuê theo thể loại. (1 đ) 
SELECT THELOAI, COUNT(MAPT) SL
FROM CHITIET_PT C JOIN SACH S ON C.MASACH = S.MASACH
GROUP BY THELOAI

