SET DATEFORMAT DMY
CREATE DATABASE QuanLyDeAn
USE QuanLyDeAn

CREATE TABLE PHONGBAN
(
MAPHG CHAR(4) PRIMARY KEY, 
TENPHG VARCHAR(20), 
TRPHG CHAR(5) , 
NGNC SMALLDATETIME
)
CREATE TABLE NHANVIEN
(
MANV CHAR(5) PRIMARY KEY, 
HOTEN VARCHAR(20), 
NGAYSINH SMALLDATETIME, 
PHAI VARCHAR(3), 
DIACHI VARCHAR(50),
MA_NQL CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
PHONG CHAR(4) FOREIGN KEY REFERENCES PHONGBAN(MAPHG),
MUCLUONG MONEY
)
CREATE TABLE THANNHAN
(
MANV CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV), 
MATN CHAR(5),
HOTENTN VARCHAR(20),
NGAYSINH SMALLDATETIME,
PHAI VARCHAR(3),
QUANHE VARCHAR(10),
CONSTRAINT PK_THANNHAN PRIMARY KEY (MANV, MATN)
)
CREATE TABLE DEAN
(
MADA CHAR(6) PRIMARY KEY,
TENDA VARCHAR(20),
DIADIEM_DA VARCHAR(20),
PHONG CHAR(4) FOREIGN KEY REFERENCES PHONGBAN(MAPHG),
NGBD SMALLDATETIME,
NGAYKT SMALLDATETIME
)
CREATE TABLE PHANCONG
(
MANV CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
MADA CHAR(6) FOREIGN KEY REFERENCES DEAN(MADA),
THOIGIAN SMALLINT
CONSTRAINT PK_PHANCONG PRIMARY KEY (MANV, MADA)
)
CREATE TABLE DD_PHONG
(
MAPHG CHAR(4) FOREIGN KEY REFERENCES PHONGBAN(MAPHG),
DIADIEM CHAR(20),
CONSTRAINT PK_DDPHONG PRIMARY KEY (MAPHG, DIADIEM)
)

ALTER TABLE PHONGBAN ADD CONSTRAINT FK_TRPHG FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)

-- câu 1: tìm tên những người trưởng phòng của từng phòng ban 
SELECT MANV, HOTEN  
FROM PHONGBAN P, NHANVIEN N
WHERE P.MAPHG = N.PHONG
-- câu 2: tìm tenda, mada, ddiem_da, phong, tenphg, maphg, trphg, ng_nhanchuc
SELECT MADA, TENDA, DIADIEM_DA, PHONG, MAPHG, TENPHG, TRPHG, NGNC
FROM PHONGBAN P, DEAN D
WHERE D.PHONG = P.MAPHG
-- câu 3: tìm tên và địa chỉ của tất cả nhân viên phòng nghiên cứu
SELECT HOTEN, DIACHI
FROM NHANVIEN N, PHONGBAN P
WHERE P.MAPHG = N.PHONG AND TENPHG = 'PHONG NGHIEN CUU'
-- câu 4: với mỗi đề án ở ha noi, liệt kê các mã số đề án (mada), mã số phòng ban chủ trì đề án (phong), họ tên trưởng phòng (hoten), cũng như địa chỉ và ngày sinh của người ấy.
SELECT MADA, MAPHG, HOTEN, DIACHI, NGAYSINH
FROM DEAN D JOIN PHONGBAN P ON D.PHONG = P.MAPHG JOIN NHANVIEN N ON N.MANV = P.TRPHG
WHERE DIADIEM_DA = 'HA NOI'
-- câu 5: với mỗi nhân viên, cho biết họ tên của nhân viên và họ tên người quản lý trực tiếp của nhân viên đó
SELECT * 
INTO NHANVIEN1
FROM NHANVIEN

SELECT A.HOTEN, B.HOTEN HOTENQL 
FROM NHANVIEN A, NHANVIEN1 B
WHERE A.MA_NQL = B.MANV
-- câu 6: cho biết tên nhân viên phòng 5 có tham gia vào đề án "sản phẩm x" 
--và nhân viên này do "nguyen thanh tung" quản lý
SELECT MANV, HOTEN
FROM NHANVIEN N, PHONGBAN P, DEAN D
WHERE N.PHONG = P.MAPHG 
AND TENPHG = 5 
AND D.PHONG = P.MAPHG
AND MADA IN(
SELECT MADA
FROM DEAN
WHERE TENDA = 'sản phẩm x')
AND TRPHG IN (
SELECT MANV
FROM NHANVIEN
WHERE HOTEN = 'nguyen thanh tung')

-- câu 7: cho biết họ tên nhân viên và tên đề án mà nhân viên ấy tham gia
-- nếu có
SELECT HOTEN, TENDA
FROM NHANVIEN N LEFT JOIN PHANCONG P 
ON N.MANV = P.MANV LEFT JOIN DEAN D
ON P.MADA = D.MADA

-- Các câu truy vấn gom nhóm
-- câu 1. với mỗi đề án, liệt kê tên đề án (tenda) và tổng số giờ 
-- làm việc 1 tuần cuả tất cả các nhân viên tham gia dự án đó.

SELECT D.MADA, TENDA, SUM(THOIGIAN) TONGSOGIO
FROM DEAN D, PHANCONG P
WHERE D.MADA = P.MADA 
GROUP BY D.MADA, TENDA

-- câu 2. với mỗi phòng ban, liệt kê tên phòng ban (tenphg)và 
-- lương trung bình của nhân viên trong phòng
SELECT MAPHG, TENPHG, AVG(MUCLUONG) LUONGTRUNGBINH
FROM PHONGBAN P JOIN NHANVIEN N ON P.MAPHG = N.PHONG
GROUP BY MAPHG, TENPHG
-- câu 3. danh sách những nhân viên (manv,hoten) không có 
-- thân nhân nào
SELECT MANV, HOTEN
FROM NHANVIEN
WHERE MANV NOT IN (
SELECT MANV
FROM THANNHAN)
-- câu 4. với những phòng ban có lương trung bình của các nhân 
-- viên thuộc phòng ban đó là >300.000, cho biết tên phòng ban và số nhân viên thuộc phòng ban đó.
SELECT MAPHG, TENPHG, COUNT(MANV) SONHANVIEN
FROM PHONGBAN P, NHANVIEN N
WHERE P.MAPHG = N.PHONG 
GROUP BY MAPHG, TENPHG
HAVING AVG(MUCLUONG) > 300000